//@version=6
strategy("EMA4-VWAP no-trail",
  slippage=2,
  overlay=true,
  pyramiding=1,
  process_orders_on_close=true,
  commission_type=strategy.commission.percent,
  commission_value=0.05,
  initial_capital=10000,
  default_qty_type=strategy.percent_of_equity,
  default_qty_value=100,
  margin_long=100,
  margin_short=100)

slM = input.float(1.8)
tpM = input.float(1.2)
ema = ta.ema(close, 4)
vwap = ta.vwap(close)
a = ta.atr(14)
longCondition = ta.crossover(ema, vwap)
shortCondition = ta.crossunder(ema, vwap)
if longCondition
    strategy.close("S")
    strategy.entry("L", strategy.long)
if shortCondition
    strategy.close("L")
    strategy.entry("S", strategy.short)
if strategy.position_size > 0
    avg = strategy.position_avg_price
    strategy.exit("Lx", from_entry="L", stop=avg - slM * a, limit=avg + tpM * a)
if strategy.position_size < 0
    avg = strategy.position_avg_price
    strategy.exit("SX", from_entry="S", stop=avg + slM * a, limit=avg - tpM * a)
